name: Documentation

on:
  workflow_run:
    workflows: ["Build Docker"]
    types: [completed]
    branches: [main, "feature/*"]

jobs:
  generate-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/docker-postbuild-generic.yml
    with:
      docker_image_repo: ${{ github.repository_owner }}/gammaspectrometer | tr '[:upper:]' '[:lower:]'
      service_name: gammaspec-dev
      working_directory: /workspace/Software
      artifact_name: documentation
      artifact_paths: |
        Documentation/Firmware/html
        Documentation/Firmware/refman.pdf
      run_script: |
        just docs